# Generated by Django 5.0.6 on 2026-05-01 10:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=20)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Stock'), ('CRYPTO', 'Cryptocurrency'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('average_cost', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('last_price_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
