# Generated by Django 5.0.6 on 2026-05-01 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='portfolios.portfolio'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['portfolio'], name='assets_portfol_7e75b2_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['symbol', 'asset_type'], name='assets_symbol_3a0672_idx'),
        ),
    ]
