# Generated by Django 5.0.9 on 2026-05-01 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Currency code must be 3 uppercase letters (ISO 4217).', regex='^[A-Z]{3}$')])),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(blank=True, max_length=8)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, help_text='Display precision (e.g. 2 for USD, 8 for BTC).')),
                ('is_crypto', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'db_table': 'currencies_currency',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Currency code must be 3 uppercase letters (ISO 4217).', regex='^[A-Z]{3}$')])),
                ('quote_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Currency code must be 3 uppercase letters (ISO 4217).', regex='^[A-Z]{3}$')])),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('rate_date', models.DateField(db_index=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'currencies_fxrate',
                'ordering': ('-rate_date', 'base_code', 'quote_code'),
                'indexes': [models.Index(fields=['base_code', 'quote_code', '-rate_date'], name='currencies__base_co_ed2fa6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='fxrate',
            constraint=models.UniqueConstraint(fields=('base_code', 'quote_code', 'rate_date'), name='uniq_fx_pair_date'),
        ),
        migrations.AddConstraint(
            model_name='fxrate',
            constraint=models.CheckConstraint(check=models.Q(('base_code', models.F('quote_code')), _negated=True), name='fx_base_quote_differ'),
        ),
    ]
