services:

  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  backend:
    build:
      target: development
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
    volumes:
      - ./backend:/app
      - media_files:/app/media
    ports:
      - "8000:8000"

  celery_worker:
    build:
      target: development
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
    volumes:
      - ./backend:/app

  celery_beat:
    build:
      target: development
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
    volumes:
      - ./backend:/app

  frontend:
    build:
      target: development
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
