# Generated by Django 5.0.9 on 2026-05-01 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_seed_system_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('currency_code', models.CharField(max_length=10)),
                ('amount_base', models.DecimalField(decimal_places=8, max_digits=20)),
                ('base_currency', models.CharField(max_length=10)),
                ('fx_rate_snapshot', models.DecimalField(decimal_places=8, max_digits=20)),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='transaction_user_id_8af7f1_idx'), models.Index(fields=['user', 'type'], name='transaction_user_id_4685bf_idx'), models.Index(fields=['user', 'category'], name='transaction_user_id_cb8cb9_idx')],
            },
        ),
    ]
