# Generated by Django 5.0.6 on 2026-05-01 10:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('PORTFOLIO_SUMMARY', 'Portfolio Summary'), ('TRANSACTION_HISTORY', 'Transaction History'), ('BUDGET_ANALYSIS', 'Budget Analysis'), ('FULL_EXPORT', 'Full Export')], max_length=30)),
                ('format', models.CharField(choices=[('CSV', 'CSV'), ('PDF', 'PDF')], max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('parameters', models.JSONField(default=dict)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-requested_at'],
            },
        ),
    ]
